export const GET_VEHICLE_MANUFACTURERS ='GET_VEHICLE_MANUFACTURERS'
export const GET_VEHICLE_MANUFACTURER ='GET_CAR_MANUFACTURER'
export const GET_VEHICLE_MODEL_DATA ='GET_VEHICLE_MODEL_DATA'
export const SET_ALERT ='SET_ALERT'
export const SET_LAST_UPDATE ='SET_LAST_UPDATE'
export const LOG_ERRORS ='LOG_ERRORS'
export const SET_ERROR ='SET_ERROR'
export const REMOVE_ERROR_FROM_STORE ='REMOVE_ERROR_FROM_STORE'
export const CHANGE_VEHICLE_FILTER ='CHANGE_VEHICLE_FILTER'
export const SET_VEHICLE_FILTERS_OPTIONS ='SET_VEHICLE_FILTERS_OPTIONS'
export const SET_VEHICLE_FILTERS_DATA ='SET_VEHICLE_FILTERS_DATA'
export const SET_GOT_RESULT='SET_GOT_RESULT'



